name: Deploy

on:
    push:
        branches:
            - production


jobs:
    deploy:
        name: Deploy
        env:
            repository: 'spatie/freek.dev'
            baseDir: '/home/forge/freek.dev'
            releasesDir: '${{ env.baseDir }}/releases-test'
            persistentDir: '${{ env.baseDir }}/persistent'
            currentDir: '${{ env.baseDir }}/current'
            newReleaseName: '${{ env.GITHUB_RUN_ID }}'
            newReleaseDir: '${{ env.releasesDir }}/${{ env.newReleaseName }}'
        runs-on: ubuntu-latest
        steps:
            -   name: Clone repository
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.KEY }}
                    script:
                      '[ -d ${{ $releasesDir }} ] || mkdir ${{ releasesDir }}]'

