name: Deploy

on:
    push:
        branches:
            - production
env:
    repository: 'spatie/freek.dev'
    baseDir: '/home/forge/freek.dev'
    newReleaseName: '${{ github.run_id }}'
jobs:
    deploy:
        name: Deploy
        env:
            releasesDir: '${{ baseDir }}/releases-test'
            persistentDir: '${{ baseDir }}/persistent'
            currentDir: '${{ baseDir }}/current'
            newReleaseDir: '${{ releasesDir }}/${{ newReleaseName }}'
        runs-on: ubuntu-latest
        steps:
            -   name: Clone repository
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.KEY }}
                    script:
                      '[ -d ${{ $releasesDir }} ] || mkdir ${{ releasesDir }}]'

