name: Deploy

on:
    push:
        branches:
            - production
env:
    repository: 'spatie/freek.dev'
    baseDir: '/home/forge/freek.dev'
    newReleaseName: '${{ github.run_id }}'
jobs:
    deploy:
        name: Deploy

        runs-on: ubuntu-latest

        steps:
            -   name: Set env
                run: |
                    echo ::set-env name=releasesDir::${{ env.baseDir }}/releases-test
                    echo ::set-env name=persistentDir::${{ env.baseDir }}/persistent
                    echo ::set-env name=currentDir::${{ env.baseDir }}/current
                    echo ::set-env name=newReleaseDir::${{ env.baseDir }}/${{ env.newReleaseName }}
            -   name: Clone repository
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.KEY }}
                    script:
                      '[ -d ${{ env.releasesDir }} ] || mkdir ${{ env.releasesDir }}]'

